// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TNLAStation.Infrastructure.Persistence;

#nullable disable

namespace TNLAStation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EpgDbContext))]
    [Migration("20260730121138_AddEncodeTaskLease")]
    partial class AddEncodeTaskLease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.DropLogFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DropCount")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_cnt");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint")
                        .HasColumnName("error_cnt");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("ParentDirectoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<long>("RecordedId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_id");

                    b.Property<long>("ScramblingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("scrambling_cnt");

                    b.HasKey("Id")
                        .HasName("pk_drop_log_files");

                    b.HasIndex("RecordedId")
                        .IsUnique()
                        .HasDatabaseName("uq_drop_log_files_recorded");

                    b.ToTable("drop_log_files", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EncodeTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Directory")
                        .HasColumnType("text")
                        .HasColumnName("directory");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("ParentDirectoryName")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<int?>("Percent")
                        .HasColumnType("integer")
                        .HasColumnName("percent");

                    b.Property<long>("RecordedId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_id");

                    b.Property<bool>("RemoveOriginal")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_original");

                    b.Property<long>("SourceVideoFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_video_file_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_encode_tasks");

                    b.HasIndex("RecordedId")
                        .HasDatabaseName("ix_encode_tasks_recorded");

                    b.HasIndex("Status", "Id")
                        .HasDatabaseName("ix_encode_tasks_queue");

                    b.ToTable("encode_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_encode_tasks_status", "status IN ('waiting', 'running')");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_type_id");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("HasLogoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_logo_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int?>("RemoteControlKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("remote_control_key_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int?>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasAlternateKey("Id", "NetworkId", "ServiceId")
                        .HasName("ak_channels_identity");

                    b.HasIndex("NetworkId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("uq_channels_network_service");

                    b.HasIndex("ChannelTypeId", "RemoteControlKeyId", "ServiceId")
                        .HasDatabaseName("ix_channels_display_order");

                    b.ToTable("channels", null, t =>
                        {
                            t.HasCheckConstraint("ck_channels_type", "channel_type IN ('GR', 'BS', 'CS', 'SKY')");

                            t.HasCheckConstraint("ck_channels_type_id", "channel_type_id = CASE channel_type WHEN 'GR' THEN 0 WHEN 'BS' THEN 1 WHEN 'CS' THEN 2 WHEN 'SKY' THEN 3 END");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgProgramEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("AudioComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("audio_component_type");

                    b.Property<int?>("AudioSamplingRate")
                        .HasColumnType("integer")
                        .HasColumnName("audio_sampling_rate");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Extended")
                        .HasColumnType("text")
                        .HasColumnName("extended");

                    b.Property<int?>("Genre1")
                        .HasColumnType("integer")
                        .HasColumnName("genre1");

                    b.Property<int?>("Genre2")
                        .HasColumnType("integer")
                        .HasColumnName("genre2");

                    b.Property<int?>("Genre3")
                        .HasColumnType("integer")
                        .HasColumnName("genre3");

                    b.Property<string>("HalfWidthDescription")
                        .HasColumnType("text")
                        .HasColumnName("half_width_description");

                    b.Property<string>("HalfWidthExtended")
                        .HasColumnType("text")
                        .HasColumnName("half_width_extended");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<string>("RawExtendedJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_extended");

                    b.Property<string>("RawHalfWidthExtendedJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_half_width_extended");

                    b.Property<string>("RelayProgramIdsJson")
                        .HasColumnType("json")
                        .HasColumnName("relay_program_ids");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer")
                        .HasColumnName("start_hour");

                    b.Property<int?>("SubGenre1")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre1");

                    b.Property<int?>("SubGenre2")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre2");

                    b.Property<int?>("SubGenre3")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre3");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<int?>("VideoComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("video_component_type");

                    b.Property<string>("VideoResolution")
                        .HasColumnType("text")
                        .HasColumnName("video_resolution");

                    b.Property<int?>("VideoStreamContent")
                        .HasColumnType("integer")
                        .HasColumnName("video_stream_content");

                    b.Property<string>("VideoType")
                        .HasColumnType("text")
                        .HasColumnName("video_type");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.HasKey("Id")
                        .HasName("pk_programs");

                    b.HasIndex("EndAt")
                        .HasDatabaseName("ix_programs_end_at");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_programs_start_at");

                    b.HasIndex("Genre1", "SubGenre1")
                        .HasDatabaseName("ix_programs_genre1");

                    b.HasIndex("Genre2", "SubGenre2")
                        .HasDatabaseName("ix_programs_genre2");

                    b.HasIndex("Genre3", "SubGenre3")
                        .HasDatabaseName("ix_programs_genre3");

                    b.HasIndex("ChannelId", "NetworkId", "ServiceId");

                    b.HasIndex("ChannelId", "StartAt", "EndAt")
                        .HasDatabaseName("ix_programs_channel_start");

                    b.HasIndex("ChannelType", "StartAt", "EndAt")
                        .HasDatabaseName("ix_programs_type_start");

                    b.HasIndex("NetworkId", "ServiceId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_programs_event");

                    b.HasIndex("Week", "StartHour", "StartAt")
                        .HasDatabaseName("ix_programs_week_hour");

                    b.ToTable("programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_programs_start_hour", "start_hour BETWEEN 0 AND 23");

                            t.HasCheckConstraint("ck_programs_time", "end_at >= start_at AND duration_ms >= 0");

                            t.HasCheckConstraint("ck_programs_week", "week BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgSyncStateEntity", b =>
                {
                    b.Property<short>("SingletonId")
                        .HasColumnType("smallint")
                        .HasColumnName("singleton_id");

                    b.Property<long>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastStreamEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_stream_event_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<bool>("NeedsFullSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("needs_full_sync");

                    b.HasKey("SingletonId")
                        .HasName("pk_epg_sync_state");

                    b.ToTable("epg_sync_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_epg_sync_state_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ManualReserveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEndLack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_end_lack");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Directory")
                        .HasColumnType("text")
                        .HasColumnName("directory");

                    b.Property<string>("Directory1")
                        .HasColumnType("text")
                        .HasColumnName("directory1");

                    b.Property<string>("Directory2")
                        .HasColumnType("text")
                        .HasColumnName("directory2");

                    b.Property<string>("Directory3")
                        .HasColumnType("text")
                        .HasColumnName("directory3");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("IsDeleteOriginalAfterEncode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delete_original_after_encode");

                    b.Property<bool>("IsTimeSpecified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_time_specified");

                    b.Property<string>("Mode1")
                        .HasColumnType("text")
                        .HasColumnName("mode1");

                    b.Property<string>("Mode2")
                        .HasColumnType("text")
                        .HasColumnName("mode2");

                    b.Property<string>("Mode3")
                        .HasColumnType("text")
                        .HasColumnName("mode3");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentDirectoryName")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<string>("ParentDirectoryName1")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name1");

                    b.Property<string>("ParentDirectoryName2")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name2");

                    b.Property<string>("ParentDirectoryName3")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name3");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<string>("RecordedFormat")
                        .HasColumnType("text")
                        .HasColumnName("recorded_format");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("TagsJson")
                        .HasColumnType("json")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_manual_reserves");

                    b.HasIndex("ProgramId")
                        .IsUnique()
                        .HasDatabaseName("uq_manual_reserves_program")
                        .HasFilter("program_id IS NOT NULL");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_manual_reserves_start_at");

                    b.ToTable("manual_reserves", null, t =>
                        {
                            t.HasCheckConstraint("ck_manual_reserves_target", "program_id IS NOT NULL OR is_time_specified");

                            t.HasCheckConstraint("ck_manual_reserves_time", "end_at > start_at");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Extended")
                        .HasColumnType("text")
                        .HasColumnName("extended");

                    b.Property<int?>("Genre1")
                        .HasColumnType("integer")
                        .HasColumnName("genre1");

                    b.Property<int?>("Genre2")
                        .HasColumnType("integer")
                        .HasColumnName("genre2");

                    b.Property<int?>("Genre3")
                        .HasColumnType("integer")
                        .HasColumnName("genre3");

                    b.Property<string>("HalfWidthDescription")
                        .HasColumnType("text")
                        .HasColumnName("half_width_description");

                    b.Property<string>("HalfWidthExtended")
                        .HasColumnType("text")
                        .HasColumnName("half_width_extended");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_protected");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recording");

                    b.Property<long?>("ManualReserveId")
                        .HasColumnType("bigint")
                        .HasColumnName("manual_reserve_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long?>("ReserveId")
                        .HasColumnType("bigint")
                        .HasColumnName("reserve_id");

                    b.Property<string>("ReserveKey")
                        .HasColumnType("text")
                        .HasColumnName("reserve_key");

                    b.Property<long?>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int?>("SubGenre1")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre1");

                    b.Property<int?>("SubGenre2")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre2");

                    b.Property<int?>("SubGenre3")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre3");

                    b.HasKey("Id")
                        .HasName("pk_recorded");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_recorded_channel");

                    b.HasIndex("IsRecording")
                        .HasDatabaseName("ix_recorded_is_recording");

                    b.HasIndex("ProgramId")
                        .IsUnique()
                        .HasDatabaseName("uq_recorded_program")
                        .HasFilter("program_id IS NOT NULL");

                    b.HasIndex("ReserveKey")
                        .HasDatabaseName("ix_recorded_reserve_key");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_recorded_rule");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_recorded_start_at");

                    b.ToTable("recorded", null, t =>
                        {
                            t.HasCheckConstraint("ck_recorded_time", "end_at >= start_at");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_recorded_history");

                    b.HasIndex("EndAt")
                        .HasDatabaseName("ix_recorded_history_end_at");

                    b.ToTable("recorded_history", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedTagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_recorded_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_recorded_tags_name");

                    b.ToTable("recorded_tags", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedTagLinkEntity", b =>
                {
                    b.Property<long>("RecordedId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("RecordedId", "TagId")
                        .HasName("pk_recorded_tag_links");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recorded_tag_links_tag");

                    b.ToTable("recorded_tag_links", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ReserveEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("IsConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("is_conflict");

                    b.Property<bool>("IsOverlap")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overlap");

                    b.Property<bool>("IsSkip")
                        .HasColumnType("boolean")
                        .HasColumnName("is_skip");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<long?>("ManualReserveId")
                        .HasColumnType("bigint")
                        .HasColumnName("manual_reserve_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<long?>("ProgramId")
                        .HasColumnType("bigint")
                        .HasColumnName("program_id");

                    b.Property<long?>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int?>("TunerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("tuner_index");

                    b.HasKey("Id")
                        .HasName("pk_reserves");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("uq_reserves_key");

                    b.HasIndex("ManualReserveId");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_reserves_rule");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_reserves_start_at");

                    b.ToTable("reserves", null, t =>
                        {
                            t.HasCheckConstraint("ck_reserves_time", "end_at > start_at");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ReserveStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EditJson")
                        .HasColumnType("text")
                        .HasColumnName("edit_json");

                    b.Property<bool>("IsOverlapCleared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_overlap_cleared");

                    b.Property<bool>("IsSkip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_skip");

                    b.HasKey("Key")
                        .HasName("pk_reserve_states");

                    b.ToTable("reserve_states", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEndLack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_end_lack");

                    b.Property<bool>("AvoidDuplicate")
                        .HasColumnType("boolean")
                        .HasColumnName("avoid_duplicate");

                    b.Property<bool>("Bs")
                        .HasColumnType("boolean")
                        .HasColumnName("bs");

                    b.Property<string>("ChannelIdsJson")
                        .HasColumnType("json")
                        .HasColumnName("channel_ids");

                    b.Property<bool>("Cs")
                        .HasColumnType("boolean")
                        .HasColumnName("cs");

                    b.Property<bool>("Description")
                        .HasColumnType("boolean")
                        .HasColumnName("description");

                    b.Property<string>("Directory")
                        .HasColumnType("text")
                        .HasColumnName("directory");

                    b.Property<string>("Directory1")
                        .HasColumnType("text")
                        .HasColumnName("directory1");

                    b.Property<string>("Directory2")
                        .HasColumnType("text")
                        .HasColumnName("directory2");

                    b.Property<string>("Directory3")
                        .HasColumnType("text")
                        .HasColumnName("directory3");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int?>("DurationMax")
                        .HasColumnType("integer")
                        .HasColumnName("duration_max");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("duration_min");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean")
                        .HasColumnName("enable");

                    b.Property<bool>("Extended")
                        .HasColumnType("boolean")
                        .HasColumnName("extended");

                    b.Property<string>("GenresJson")
                        .HasColumnType("json")
                        .HasColumnName("genres");

                    b.Property<bool>("Gr")
                        .HasColumnType("boolean")
                        .HasColumnName("gr");

                    b.Property<string>("HalfWidthIgnoreKeyword")
                        .HasColumnType("text")
                        .HasColumnName("half_width_ignore_keyword");

                    b.Property<string>("HalfWidthKeyword")
                        .HasColumnType("text")
                        .HasColumnName("half_width_keyword");

                    b.Property<bool>("IgnoreDescription")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_description");

                    b.Property<bool>("IgnoreExtended")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_extended");

                    b.Property<bool>("IgnoreKeyCaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_key_cs");

                    b.Property<bool>("IgnoreKeyRegularExpression")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_key_reg_exp");

                    b.Property<string>("IgnoreKeyword")
                        .HasColumnType("text")
                        .HasColumnName("ignore_keyword");

                    b.Property<bool>("IgnoreName")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_name");

                    b.Property<bool>("IsDeleteOriginalAfterEncode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delete_original_after_encode");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<bool>("IsTimeSpecification")
                        .HasColumnType("boolean")
                        .HasColumnName("is_time_specification");

                    b.Property<bool>("KeyCaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("key_cs");

                    b.Property<bool>("KeyRegularExpression")
                        .HasColumnType("boolean")
                        .HasColumnName("key_reg_exp");

                    b.Property<string>("Keyword")
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("Mode1")
                        .HasColumnType("text")
                        .HasColumnName("mode1");

                    b.Property<string>("Mode2")
                        .HasColumnType("text")
                        .HasColumnName("mode2");

                    b.Property<string>("Mode3")
                        .HasColumnType("text")
                        .HasColumnName("mode3");

                    b.Property<bool>("Name")
                        .HasColumnType("boolean")
                        .HasColumnName("name");

                    b.Property<string>("ParentDirectoryName")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<string>("ParentDirectoryName1")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name1");

                    b.Property<string>("ParentDirectoryName2")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name2");

                    b.Property<string>("ParentDirectoryName3")
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name3");

                    b.Property<int?>("PeriodToAvoidDuplicate")
                        .HasColumnType("integer")
                        .HasColumnName("period_to_avoid_duplicate");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("RecordedFormat")
                        .HasColumnType("text")
                        .HasColumnName("recorded_format");

                    b.Property<string>("SearchPeriodsJson")
                        .HasColumnType("json")
                        .HasColumnName("search_periods");

                    b.Property<bool>("Sky")
                        .HasColumnType("boolean")
                        .HasColumnName("sky");

                    b.Property<string>("TagsJson")
                        .HasColumnType("json")
                        .HasColumnName("tags");

                    b.Property<string>("TimesJson")
                        .HasColumnType("json")
                        .HasColumnName("times");

                    b.Property<long>("UpdateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("update_cnt");

                    b.HasKey("Id")
                        .HasName("pk_rules");

                    b.HasIndex("Enable")
                        .HasDatabaseName("ix_rules_enable");

                    b.HasIndex("HalfWidthKeyword")
                        .HasDatabaseName("ix_rules_half_width_keyword");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ThumbnailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("ParentDirectoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<long>("RecordedId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_id");

                    b.HasKey("Id")
                        .HasName("pk_thumbnails");

                    b.HasIndex("RecordedId")
                        .HasDatabaseName("ix_thumbnails_recorded");

                    b.ToTable("thumbnails", (string)null);
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.VideoFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentDirectoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_directory_name");

                    b.Property<long>("RecordedId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_video_files");

                    b.HasIndex("RecordedId")
                        .HasDatabaseName("ix_video_files_recorded");

                    b.ToTable("video_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_video_files_type", "type IN ('ts', 'encoded')");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.DropLogFileEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.RecordedEntity", "Recorded")
                        .WithOne("DropLogFile")
                        .HasForeignKey("TNLAStation.Infrastructure.Persistence.DropLogFileEntity", "RecordedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drop_log_files_recorded");

                    b.Navigation("Recorded");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgProgramEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", "ChannelEntity")
                        .WithMany("Programs")
                        .HasForeignKey("ChannelId", "NetworkId", "ServiceId")
                        .HasPrincipalKey("Id", "NetworkId", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_channel");

                    b.Navigation("ChannelEntity");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedTagLinkEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.RecordedEntity", "Recorded")
                        .WithMany("TagLinks")
                        .HasForeignKey("RecordedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorded_tag_links_recorded");

                    b.HasOne("TNLAStation.Infrastructure.Persistence.RecordedTagEntity", "Tag")
                        .WithMany("Links")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorded_tag_links_tag");

                    b.Navigation("Recorded");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ReserveEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.ManualReserveEntity", "ManualReserve")
                        .WithMany()
                        .HasForeignKey("ManualReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reserves_manual_reserve");

                    b.Navigation("ManualReserve");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.ThumbnailEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.RecordedEntity", "Recorded")
                        .WithMany("Thumbnails")
                        .HasForeignKey("RecordedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thumbnails_recorded");

                    b.Navigation("Recorded");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.VideoFileEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.RecordedEntity", "Recorded")
                        .WithMany("VideoFiles")
                        .HasForeignKey("RecordedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_files_recorded");

                    b.Navigation("Recorded");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedEntity", b =>
                {
                    b.Navigation("DropLogFile");

                    b.Navigation("TagLinks");

                    b.Navigation("Thumbnails");

                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.RecordedTagEntity", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
