// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TNLAStation.Infrastructure.Persistence;

#nullable disable

namespace TNLAStation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EpgDbContext))]
    [Migration("20260720083307_InitialEpg")]
    partial class InitialEpg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_type_id");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("HasLogoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_logo_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int?>("RemoteControlKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("remote_control_key_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int?>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasAlternateKey("Id", "NetworkId", "ServiceId")
                        .HasName("ak_channels_identity");

                    b.HasIndex("NetworkId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("uq_channels_network_service");

                    b.HasIndex("ChannelTypeId", "RemoteControlKeyId", "ServiceId")
                        .HasDatabaseName("ix_channels_display_order");

                    b.ToTable("channels", null, t =>
                        {
                            t.HasCheckConstraint("ck_channels_type", "channel_type IN ('GR', 'BS', 'CS', 'SKY')");

                            t.HasCheckConstraint("ck_channels_type_id", "channel_type_id = CASE channel_type WHEN 'GR' THEN 0 WHEN 'BS' THEN 1 WHEN 'CS' THEN 2 WHEN 'SKY' THEN 3 END");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgProgramEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("AudioComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("audio_component_type");

                    b.Property<int?>("AudioSamplingRate")
                        .HasColumnType("integer")
                        .HasColumnName("audio_sampling_rate");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Extended")
                        .HasColumnType("text")
                        .HasColumnName("extended");

                    b.Property<int?>("Genre1")
                        .HasColumnType("integer")
                        .HasColumnName("genre1");

                    b.Property<int?>("Genre2")
                        .HasColumnType("integer")
                        .HasColumnName("genre2");

                    b.Property<int?>("Genre3")
                        .HasColumnType("integer")
                        .HasColumnName("genre3");

                    b.Property<string>("HalfWidthDescription")
                        .HasColumnType("text")
                        .HasColumnName("half_width_description");

                    b.Property<string>("HalfWidthExtended")
                        .HasColumnType("text")
                        .HasColumnName("half_width_extended");

                    b.Property<string>("HalfWidthName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("half_width_name");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<string>("RawExtendedJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_extended");

                    b.Property<string>("RawHalfWidthExtendedJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_half_width_extended");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer")
                        .HasColumnName("start_hour");

                    b.Property<int?>("SubGenre1")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre1");

                    b.Property<int?>("SubGenre2")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre2");

                    b.Property<int?>("SubGenre3")
                        .HasColumnType("integer")
                        .HasColumnName("sub_genre3");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<int?>("VideoComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("video_component_type");

                    b.Property<string>("VideoResolution")
                        .HasColumnType("text")
                        .HasColumnName("video_resolution");

                    b.Property<int?>("VideoStreamContent")
                        .HasColumnType("integer")
                        .HasColumnName("video_stream_content");

                    b.Property<string>("VideoType")
                        .HasColumnType("text")
                        .HasColumnName("video_type");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.HasKey("Id")
                        .HasName("pk_programs");

                    b.HasIndex("EndAt")
                        .HasDatabaseName("ix_programs_end_at");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_programs_start_at");

                    b.HasIndex("Genre1", "SubGenre1")
                        .HasDatabaseName("ix_programs_genre1");

                    b.HasIndex("Genre2", "SubGenre2")
                        .HasDatabaseName("ix_programs_genre2");

                    b.HasIndex("Genre3", "SubGenre3")
                        .HasDatabaseName("ix_programs_genre3");

                    b.HasIndex("ChannelId", "NetworkId", "ServiceId");

                    b.HasIndex("ChannelId", "StartAt", "EndAt")
                        .HasDatabaseName("ix_programs_channel_start");

                    b.HasIndex("ChannelType", "StartAt", "EndAt")
                        .HasDatabaseName("ix_programs_type_start");

                    b.HasIndex("NetworkId", "ServiceId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_programs_event");

                    b.HasIndex("Week", "StartHour", "StartAt")
                        .HasDatabaseName("ix_programs_week_hour");

                    b.ToTable("programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_programs_start_hour", "start_hour BETWEEN 0 AND 23");

                            t.HasCheckConstraint("ck_programs_time", "end_at >= start_at AND duration_ms >= 0");

                            t.HasCheckConstraint("ck_programs_week", "week BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgSyncStateEntity", b =>
                {
                    b.Property<short>("SingletonId")
                        .HasColumnType("smallint")
                        .HasColumnName("singleton_id");

                    b.Property<long>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastStreamEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_stream_event_at");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<bool>("NeedsFullSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("needs_full_sync");

                    b.HasKey("SingletonId")
                        .HasName("pk_epg_sync_state");

                    b.ToTable("epg_sync_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_epg_sync_state_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgProgramEntity", b =>
                {
                    b.HasOne("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", "ChannelEntity")
                        .WithMany("Programs")
                        .HasForeignKey("ChannelId", "NetworkId", "ServiceId")
                        .HasPrincipalKey("Id", "NetworkId", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_channel");

                    b.Navigation("ChannelEntity");
                });

            modelBuilder.Entity("TNLAStation.Infrastructure.Persistence.EpgChannelEntity", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
